version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - GOOS=linux GOARCH=amd64 go build src/hello.go
  post_build:
    commands:
      - echo Build finished on `date`

artifacts:
  files:
    - hello
